In [1]:
# from pmdarima import auto_arima
# from src.utils import process_data

# _, df, _ = process_data()

# model = auto_arima(df['y'], seasonal=True, m=1, stepwise=True, trace=True)
# print(model.summary())

In [2]:
from src.utils import process_data
df_1, df_2, df_3 = process_data()

In [3]:
df_1

       unique_id                  ds        y
0           HUFL 2016-07-01 00:00:00  5.82700
1           HUFL 2016-07-01 01:00:00  5.69300
2           HUFL 2016-07-01 02:00:00  5.15700
3           HUFL 2016-07-01 03:00:00  5.09000
4           HUFL 2016-07-01 04:00:00  5.35800
...          ...                 ...      ...
243875      OT.1 2018-06-26 15:00:00  6.05272
243876      OT.1 2018-06-26 16:00:00  6.05272
243877      OT.1 2018-06-26 17:00:00  6.05272
243878      OT.1 2018-06-26 18:00:00  6.05272
243879      OT.1 2018-06-26 19:00:00  6.05272

[243880 rows x 3 columns]

In [4]:
df_2

       unique_id                  ds         y
0           HUFL 2016-07-01 00:00:00  5.827000
1           HUFL 2016-07-01 01:00:00  5.693000
2           HUFL 2016-07-01 02:00:00  5.157000
3           HUFL 2016-07-01 03:00:00  5.090000
4           HUFL 2016-07-01 04:00:00  5.358000
...          ...                 ...       ...
233445      OT.1 2018-05-26 14:00:00  4.615655
233446      OT.1 2018-05-26 15:00:00  4.615655
233447      OT.1 2018-05-26 16:00:00  4.615655
233448      OT.1 2018-05-26 17:00:00  4.615655
233449      OT.1 2018-05-26 18:00:00  4.615655

[233450 rows x 3 columns]

In [5]:
df_3

      unique_id                  ds         y
0          HUFL 2018-05-26 19:00:00   9.91300
1          HUFL 2018-05-26 20:00:00  10.24800
2          HUFL 2018-05-26 21:00:00   8.97500
3          HUFL 2018-05-26 22:00:00   9.98000
4          HUFL 2018-05-26 23:00:00  12.79300
...         ...                 ...       ...
10425      OT.1 2018-06-26 15:00:00   6.05272
10426      OT.1 2018-06-26 16:00:00   6.05272
10427      OT.1 2018-06-26 17:00:00   6.05272
10428      OT.1 2018-06-26 18:00:00   6.05272
10429      OT.1 2018-06-26 19:00:00   6.05272

[10430 rows x 3 columns]

In [2]:
from src.hup_statsmacrocast import HupStatsMacrocast

c:\Users\giust\projects\volatility-forecasting-master\fore_venv\Lib\site-packages\statsforecast\core.py:26: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

In [3]:
hsm = HupStatsMacrocast(normalization=True)

In [4]:
hsm.predict()

Currently running: [7, 'identity', 'AutoARIMA']

In [ ]:
hsm.cross_validation()

Currently running: [7, 'identity', 'AutoARIMA']

In [ ]:
hsm.best_results_plots(result="forecast", actual=True)

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\giust\\projects\\volatility-forecasting-master\\Nixtla\\StatsForecast\\results_norm\\horizon=7\\SF_container_identity\\stats_training\\stats_training_results_(nw=2364)\\cv_df_(nw=2364).csv'

In [ ]:
hsm.best_results_metric_dataframe()

   metric unique_id  metric_value                   best_model transformation
0     mae      HUFL      0.035592                      AutoETS       identity
1     mae    HUFL.1      0.241681              HistoricAverage       identity
2     mae      HULL      0.107978                SeasNaive_sl7       identity
3     mae    HULL.1      0.154973                   GARCH(1,1)       identity
4     mae      LUFL      0.240922              HistoricAverage       identity
5     mae    LUFL.1      0.095795  SeasNaive_sl1_HoltWinters_x       identity
6     mae      LULL      0.026363                      AutoETS       identity
7     mae    LULL.1      0.120074                        ARIMA       identity
8     mae      MUFL      0.165930                   GARCH(2,1)       identity
9     mae    MUFL.1      0.128820  SeasNaive_sl1_HoltWinters_x       identity
10    mae      MULL      0.296353                SeasNaive_sl7       identity
11    mae    MULL.1      0.298819                SeasNaive_sl7       identity
12    mae        OT      0.109074              HistoricAverage       identity
13    mae      OT.1      0.221284              HistoricAverage       identity